services:
  #  playit:
  #    image: ghcr.io/playit-cloud/playit-agent:0.16
  #    network_mode: host
  #    environment:
  #      - SECRET_KEY=
  mc-modpack-installer:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.modinstaller
    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./scripts:/scripts
    environment:
      MODRINTH_URL: ${MODRINTH_URL}
      SERVER_WORLDNAME: ${SERVER_WORLDNAME}
    entrypoint: ["/bin/sh", "/scripts/install-modpack.sh"]

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "6G"
      SERVER_WORLDNAME: ${SERVER_WORLDNAME}
      LEVEL: ${SERVER_WORLDNAME}
      SERVER_NAME: ${SERVER_NAME}
      MOTD: ${SERVER_MOTD}
      ICON: ${SERVER_ICON}
      RCON_PASSWORD: ${RCON_PASSWORD}
      ALLOW_FLIGHT: "true"
      SPAWN_MONSTERS: "false"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_WHITELIST: "false"
      DEBUG: "false"
    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./scripts/wait-for-modpack.sh:/wait-for-modpack.sh
    entrypoint: ["/bin/sh", "/wait-for-modpack.sh"]
    command: []
    ports:
      - "25565:25565"
      - "25575:25575"
    depends_on:
      - mc-modpack-installer
    restart: unless-stopped

  mc-backup:
    image: itzg/mc-backup:latest
    container_name: mc-backup
    environment:
      BACKUP_NAME: ${SERVER_WORLDNAME}
      PRUNE_BACKUPS_COUNT: ${KEEP_BACKUPS}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_HOST: mc
      TZ: ${TZ}
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mc
    restart: unless-stopped
