services:
  mc-modpack-installer:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.modinstaller
    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./scripts:/scripts
    environment:
      MODRINTH_URL: ${MODRINTH_URL:-https://cdn.modrinth.com/data/Jkb29YJU/versions/UIAtF4al/COBBLEVERSE%201.5.5.mrpack}
      SERVER_WORLDNAME: ${SERVER_WORLDNAME:-CobbleVerse}
    entrypoint: ["/bin/sh", "/scripts/install-modpack.sh"]

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      FABRIC_LOADER_VERSION: "0.17.2"
      FABRIC_LAUNCHER_VERSION: "1.1.0"
      MEMORY: "6G"
      SERVER_WORLDNAME: ${SERVER_WORLDNAME:-CobbleVerse}
      LEVEL: ${SERVER_WORLDNAME:-CobbleVerse}
      ENABLE_WHITELIST: "false"
      DEBUG: ${DEBUG:-False}
      SERVER_NAME: ${SERVER_NAME_-CobbleVerse}
      ICON: ${SERVER_ICON:-}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT:-True}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS:-False}

    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./worlds:/data/worlds
      - ./scripts/wait-for-modpack.sh:/wait-for-modpack.sh
    entrypoint: ["/bin/sh", "/wait-for-modpack.sh"]
    command: []
    ports:
      - "25565:25565"
    depends_on:
      - mc-modpack-installer
    restart: unless-stopped
